# Generated by Django 3.2.13 on 2022-08-28 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FunixRelativeDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('block_id', models.CharField(max_length=255, null=True)),
                ('type', models.CharField(max_length=255)),
                ('date', models.DateField(default=django.utils.timezone.now, editable=False)),
                ('index', models.IntegerField()),
            ],
        ),
    ]
